
extern void (*token_processing)(char token);
extern int position_to_write;

extern void serial_setup();

extern int read_initialization();
extern int process_initialization_data();

extern void read_serial();
extern void store_token(char token, char destination[], int size, int *updated);


#define DEFAULT_TOKEN_PROCESSING      determine_extraction_type

#define READ_FLAPS_POSITION           DEFAULT_TOKEN_PROCESSING
#define READ_SPOILERS_POSITION        DEFAULT_TOKEN_PROCESSING
#define READ_SPOILERS_ARMED           DEFAULT_TOKEN_PROCESSING

#define READ_COM1_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_COM1_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_COM2_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_COM2_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_NAV1_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_NAV1_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_NAV2_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_NAV2_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_TRANSPONDER_CODE         DEFAULT_TOKEN_PROCESSING
#define READ_COM1_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_COM2_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_NAV1_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_NAV2_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_REFERENCE_SPEED          DEFAULT_TOKEN_PROCESSING
#define READ_SPEED_HOLD_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_REFERENCE_HEADING        DEFAULT_TOKEN_PROCESSING
#define READ_HEADING_HOLD_ACTIVE      DEFAULT_TOKEN_PROCESSING
#define READ_COURSE                   DEFAULT_TOKEN_PROCESSING
#define READ_AP_STATUS                DEFAULT_TOKEN_PROCESSING
#define READ_A_THR_STATUS             DEFAULT_TOKEN_PROCESSING
#define READ_REFERENCE_ALTITUDE       DEFAULT_TOKEN_PROCESSING
#define READ_REFERENCE_VERTICAL_SPEED DEFAULT_TOKEN_PROCESSING
#define READ_ALTITUDE_HOLD_ACTIVE     DEFAULT_TOKEN_PROCESSING
#define READ_APR_HOLD                 DEFAULT_TOKEN_PROCESSING
#define READ_NAV_HOLD                 DEFAULT_TOKEN_PROCESSING
#define READ_GLIDESLOPE_HOLD          DEFAULT_TOKEN_PROCESSING

#define READ_ELEVATOR_TRIM            DEFAULT_TOKEN_PROCESSING
#define READ_PARKING_BRAKE_STATUS     DEFAULT_TOKEN_PROCESSING

#define READ_GEAR_POSITION            DEFAULT_TOKEN_PROCESSING
#define READ_GEAR_RETRACTABLE         DEFAULT_TOKEN_PROCESSING
#define READ_RUDDERT_TRIM             DEFAULT_TOKEN_PROCESSING
#define READ_PARKING_BRAKE_STATUS     DEFAULT_TOKEN_PROCESSING

#define READ_AIRSPEED                 DEFAULT_TOKEN_PROCESSING
#define READ_GROUND_SPEED             DEFAULT_TOKEN_PROCESSING
#define READ_ALTITUDE                 DEFAULT_TOKEN_PROCESSING
#define READ_HEADING                  DEFAULT_TOKEN_PROCESSING
#define READ_GROUND_CLEARANCE         DEFAULT_TOKEN_PROCESSING
#define READ_AIRCRAFT_ON_GROUND       DEFAULT_TOKEN_PROCESSING
#define READ_ILS_LOC_OFFSET           DEFAULT_TOKEN_PROCESSING
#define READ_ILS_GS_OFFSET            DEFAULT_TOKEN_PROCESSING
#define READ_PITCH                    DEFAULT_TOKEN_PROCESSING
#define READ_ROLL                     DEFAULT_TOKEN_PROCESSING
#define READ_ALTIMETER_SETTING        DEFAULT_TOKEN_PROCESSING
#define READ_OVERSPEED_WARNING        DEFAULT_TOKEN_PROCESSING
#define READ_STALL_WARNING            DEFAULT_TOKEN_PROCESSING
#define READ_G_FORCE                  DEFAULT_TOKEN_PROCESSING
#define READ_ANGLE_OF_ATTACK          DEFAULT_TOKEN_PROCESSING
#define READ_TOGA                     DEFAULT_TOKEN_PROCESSING

#define READ_ENGINE_1_RPM             DEFAULT_TOKEN_PROCESSING
#define READ_ENGINE_2_RPM             DEFAULT_TOKEN_PROCESSING
#define READ_THROTTLE_POSITION_1      DEFAULT_TOKEN_PROCESSING
#define READ_THROTTLE_POSITION_2      DEFAULT_TOKEN_PROCESSING

#define READ_EGT_ENGINE_1             DEFAULT_TOKEN_PROCESSING
#define READ_EGT_ENGINE_2             DEFAULT_TOKEN_PROCESSING
#define READ_FUEL_FLOW_ENGINE_1       DEFAULT_TOKEN_PROCESSING
#define READ_FUEL_FLOW_ENGINE_2       DEFAULT_TOKEN_PROCESSING

#define READ_LEFT_FUEL                DEFAULT_TOKEN_PROCESSING
#define READ_CENTRAL_FUEL             DEFAULT_TOKEN_PROCESSING
#define READ_RIGHT_FUEL               DEFAULT_TOKEN_PROCESSING
#define READ_X_FEED_VALVE             DEFAULT_TOKEN_PROCESSING

////////////////////////////////////////////////////////////////////////////////

// Radio Panel
#define READ_COM1_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_COM1_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_COM2_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_COM2_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_NAV1_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_NAV1_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_NAV2_FREQ                DEFAULT_TOKEN_PROCESSING
#define READ_NAV2_SB_FREQ             DEFAULT_TOKEN_PROCESSING
#define READ_TRANSPONDER_CODE         DEFAULT_TOKEN_PROCESSING
#define READ_COM1_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_COM2_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_NAV1_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING
#define READ_NAV2_SOUND_ACTIVE        DEFAULT_TOKEN_PROCESSING

// Gear Panel
#define READ_GEAR_RETRACTABLE         read_gear_retractable
#define READ_GEAR_POSITION            read_gear_position

// Trim Panel
#define READ_ELEVATOR_TRIM            DEFAULT_TOKEN_PROCESSING
#define READ_RUDDERT_TRIM             DEFAULT_TOKEN_PROCESSING
