#define SWAP_COM1     "A06"
#define SWAP_COM2     "A12"
#define SWAP_NAV1     "A18"
#define SWAP_NAV2     "A24"

#define TOGGLE_AP       "B01"
#define TOGGLE_A_THR    "B34"

#define TOGGLE_APR      "B08"
#define TOGGLE_LOC      "B10"

#define TOGGLE_FD       "B30"
#define TOGGLE_NAV_GPS  "A54"

#define SPEED_HEADING_HOLD        "B26"
#define SET_REFERENCE_SPEED       "B22"
#define INCREMENT_REFERENCE_SPEED "B15"
#define DECREMENT_REFERENCE_SPEED "B16"

#define TOGGLE_HEADING_HOLD         "B04"
#define SET_REFERENCE_HEADING       "A59"
#define INCREMENT_REFERENCE_HEADING "A57"
#define DECREMENT_REFERENCE_HEADING "A58"

#define SET_REFERENCE_COURSE        "B33"
#define INCREMENT_REFERENCE_COURSE  "A56"
#define DECREMENT_REFERENCE_COURSE  "A55"

#define TOGGLE_ALTITUDE_HOLD         "B05"
#define SET_REFERENCE_ALTITUDE       "B32"
#define INCREMENT_REFERENCE_ALTITUDE "B11"
#define DECREMENT_REFERENCE_ALTITUDE "B12"

#define INCREMENT_REFERENCE_VERTICAL_SPEED "B13"
#define DECREMENT_REFERENCE_VERTICAL_SPEED "B14"

#define SET_COM1_TO_TRANSMIT  "A45"
#define SET_COM2_TO_TRANSMIT  "A46"
#define TOGGLE_NAV1_ID        "A48"
#define TOGGLE_NAV2_ID        "A49"

#define INCREMENT_COM1_MHZ    "A02"
#define INCREMENT_COM1_KHZ    "A04"
#define DECREMENT_COM1_MHZ    "A01"
#define DECREMENT_COM1_KHZ    "A03"

#define INCREMENT_COM2_MHZ    "A08"
#define INCREMENT_COM2_KHZ    "A10"
#define DECREMENT_COM2_MHZ    "A07"
#define DECREMENT_COM2_KHZ    "A09"

#define INCREMENT_NAV1_MHZ    "A14"
#define INCREMENT_NAV1_KHZ    "A16"
#define DECREMENT_NAV1_MHZ    "A13"
#define DECREMENT_NAV1_KHZ    "A15"

#define INCREMENT_NAV2_MHZ    "A20"
#define INCREMENT_NAV2_KHZ    "A22"
#define DECREMENT_NAV2_MHZ    "A19"
#define DECREMENT_NAV2_KHZ    "A21"

#define INCREMENT_TRANSPONDER_DIGIT1 "A34"
#define INCREMENT_TRANSPONDER_DIGIT2 "A35"
#define INCREMENT_TRANSPONDER_DIGIT3 "A36"
#define INCREMENT_TRANSPONDER_DIGIT4 "A37"
#define DECREMENT_TRANSPONDER_DIGIT1 "A38"
#define DECREMENT_TRANSPONDER_DIGIT2 "A39"
#define DECREMENT_TRANSPONDER_DIGIT3 "A40"
#define DECREMENT_TRANSPONDER_DIGIT4 "A41"

#define GEAR_UP               "C01"
#define GEAR_DOWN             "C02"
#define TOGGLE_PARKING_BRAKE  "C04"
#define PARKING_BRAKE_OFF     "C040"
#define PARKING_BRAKE_ON      "C041"

#define TRIM_RUDDER_RIGHT     "C28"
#define TRIM_RUDDER_LEFT      "C27"

#define TRIM_ELEVATOR_UP      "C18"
#define TRIM_ELEVATOR_DOWN    "C19"

#define INCREMENT_FLAPS       "C14"
#define DECREMENT_FLAPS       "C15"
#define RETRACT_FLAPS         "C13"

#define ARM_SPOILERS_ON       "C20"
#define ARM_SPOILERS_OFF      "C21"

#define EXTEND_SPOILERS       "C23"
#define RETRACT_SPOILERS      "C24"
