#define RADIO_AP_EXTRACTIONS                '='
#define COM_1_FREQ_EXTRACTION               'A'
#define COM_1_SB_FREQ_EXTRACTION            'B'
#define COM_2_FREQ_EXTRACTION               'C'
#define COM_2_SB_FREQ_EXTRACTION            'D'
#define NAV_1_FREQ_EXTRACTION               'E'
#define NAV_1_SB_FREQ_EXTRACTION            'F'
#define NAV_2_FREQ_EXTRACTION               'G'
#define NAV_2_SB_FREQ_EXTRACTION            'H'
#define TRANSPONDER_CODE_EXTRACTION         'J'
#define COM_1_SOUND_ACTIVE_EXTRACTION       'M'
#define COM_2_SOUND_ACTIVE_EXTRACTION       'N'
#define NAV_1_SOUND_ACTIVE_EXTRACTION       'P'
#define NAV_2_SOUND_ACTIVE_EXTRACTION       'Q'
#define AP_ACTIVE_EXTRACTION                'a'
#define AP_ALTITUDE_SET_EXTRACTION          'b'
#define AP_VERTICAL_SPEED_SET_EXTRACTION    'c'
#define AP_HEADING_SET_EXTRACTION           'd'
#define AP_COURSE_SET_EXTRACTION            'e'
#define AP_AIRSPEED_SET_EXTRACTION          'f'
#define AP_HEADING_LOCK_ACTIVE_EXTRACTION   'j'
#define AP_ALTITUDE_LOCK_ACTIVE_EXTRACTION  'k'
#define AP_GPS_DRIVES_NAV_1_EXTRACTION      'l'
#define AP_APR_HOLD_ACTIVE_EXTRACTION       'm'
#define AP_NAV_HOLD_EXTRACTION              'o'
#define AP_FD_EXTRACTION                    'q'
#define AP_GLIDESLOPE_HOLD_EXTRACTION       'r'
#define AP_AIRSPEED_LOCK_ACTIVE_EXTRACTION  's'
#define A_THR_ARMED_EXTRACTION              't'


#define INDICATIONS_SYSTEM_1_EXTRACTIONS    '<'
#define FLAPS_POSITION_EXTRACTION           'G'
#define TRIM_POSITION_EXTRACTION            'H'
#define SPOILERS_POSITON_EXTRACTION         'i'
#define SPOILERS_ARMED_EXTRACTION           'j'
#define PARK_BRAKE_POSITION                 'q'



#define SYSTEM_2_OTHERS_EXTRACTIONS         '?'
#define GEAR_POSITION_EXTRACTION            'Y'
#define GEAR_RETRACTABLE_EXTRACTION         'b'           
#define RUDDER_TRIM_EXTRACTION              'Z'         
